# Generated by Django 6.1.1 on 2026-09-27 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(default='S/N', max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255, verbose_name='ponto de referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('foto', models.ImageField(upload_to='denuncias/%Y/%m/')),
                ('anonima', models.BooleanField(default=False, verbose_name='anônima')),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('ACEITA', 'Aceita'), ('RESOLVIDA', 'Resolvida'), ('REJEITADA', 'Rejeitada')], default='ENVIADA', max_length=10)),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='data da ocorrência')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('encaminhada_orgao', models.BooleanField(default=False, verbose_name='encaminhada ao órgão')),
                ('data_encaminhamento', models.DateField(blank=True, null=True)),
                ('excluida', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.local')),
            ],
            options={
                'verbose_name': 'denúncia',
                'verbose_name_plural': 'denúncias',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('ENVIADA', 'Enviada'), ('ACEITA', 'Aceita'), ('RESOLVIDA', 'Resolvida'), ('REJEITADA', 'Rejeitada')], max_length=10, null=True)),
                ('status_novo', models.CharField(choices=[('ENVIADA', 'Enviada'), ('ACEITA', 'Aceita'), ('RESOLVIDA', 'Resolvida'), ('REJEITADA', 'Rejeitada')], max_length=10)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='denuncias.denuncia')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='LogAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ALTERACAO_STATUS', 'Alteração de status'), ('EXCLUSAO_DENUNCIA', 'Exclusão de denúncia'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('BLOQUEIO_USUARIO', 'Bloqueio de usuário'), ('DESBLOQUEIO_USUARIO', 'Desbloqueio de usuário'), ('EXCLUSAO_USUARIO', 'Exclusão de usuário'), ('OUTRO', 'Outro')], max_length=20, verbose_name='ação')),
                ('entidade', models.CharField(blank=True, max_length=50)),
                ('id_entidade', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log administrativo',
                'verbose_name_plural': 'logs administrativos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('uf', models.CharField(default='RN', max_length=2)),
                ('codigo_ibge', models.CharField(blank=True, max_length=7, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'uf'), name='uk_municipio_nome')],
            },
        ),
        migrations.AddField(
            model_name='local',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais', to='denuncias.municipio'),
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='denuncias.denuncia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('denuncia', 'usuario'), name='uk_curtida_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(fields=('municipio', 'bairro', 'logradouro', 'numero'), name='uk_local_endereco'),
        ),
    ]
